// flow-typed signature: 3553356779b4c1e1388bf8326f992a2b
// flow-typed version: <<STUB>>/inquirer-directory_v^2.1.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inquirer-directory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inquirer-directory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inquirer-directory/example' {
  declare module.exports: any;
}

declare module 'inquirer-directory/test/helpers/readline' {
  declare module.exports: any;
}

declare module 'inquirer-directory/test/spec/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inquirer-directory/example.js' {
  declare module.exports: $Exports<'inquirer-directory/example'>;
}
declare module 'inquirer-directory/index' {
  declare module.exports: $Exports<'inquirer-directory'>;
}
declare module 'inquirer-directory/index.js' {
  declare module.exports: $Exports<'inquirer-directory'>;
}
declare module 'inquirer-directory/test/helpers/readline.js' {
  declare module.exports: $Exports<'inquirer-directory/test/helpers/readline'>;
}
declare module 'inquirer-directory/test/spec/index.spec.js' {
  declare module.exports: $Exports<'inquirer-directory/test/spec/index.spec'>;
}
